#!/bin/bash
# Universal MCP Installation Script
# Generated by Universal MCP Discovery System v4.0

set -e

echo "🚀 Installing Universal MCP Ecosystem v3.0..."
echo "📁 Project: $(pwd)"
echo "🎯 Installing 8 MCP servers"
echo ""

# Install Claude Flow 2.0 with MCP v3.0
echo "📦 Installing Claude Flow 2.0 with Enhanced MCP Ecosystem..."
npx --yes claude-flow@2.0.0 init --claude --webui --mcp-v3

# Create MCP configuration
echo "⚙️  Creating MCP configuration..."
mkdir -p .mcp/servers
cp mcp-config.json .mcp/config.json

# Start core services
echo "🔧 Starting core MCP services..."
npx claude-flow start --core

# Health check
echo "🏥 Running health checks..."
npx claude-flow mcp health-check

echo ""
echo "✅ Universal MCP Ecosystem installed successfully!"
echo "🌐 Dashboard: http://localhost:3000"
echo "📚 Documentation: ./README.md"
echo ""
echo "High Priority Servers Installed:"
echo "  ✓ filesystem (core)"\necho "  ✓ http (core)"\necho "  ✓ git (core)"\necho "  ✓ npm (package-manager)"\necho "  ✓ docker (containerization)"\necho "  ✓ github (ci-cd)"
echo ""
echo "Next steps:"
echo "1. Access the dashboard to manage servers"
echo "2. Review configuration in mcp-config.json"
echo "3. Enable additional servers as needed"
